import type { Course, Category, Stamp } from "@/types/dream";

export const COURSES: Course[] = [
  {
    id: "aggressive",
    label: "積極コース",
    icon: "🔥",
    multiplier: 6.7275,
    multiplier50: 117.3909,
    annualRate: 0.10,
    indexName: "NASDAQ100",
    color: "text-red-500",
  },
  {
    id: "standard",
    label: "標準コース",
    icon: "🌟",
    multiplier: 4.6610,
    multiplier50: 46.9016,
    annualRate: 0.08,
    indexName: "S&P500",
    color: "text-amber-500",
  },
  {
    id: "balanced",
    label: "バランスコース",
    icon: "⚖️",
    multiplier: 3.3066,
    multiplier50: 29.4570,
    annualRate: 0.07,
    indexName: "全世界株式(7%)",
    color: "text-blue-500",
  },
  {
    id: "conservative",
    label: "堅実コース",
    icon: "🐢",
    multiplier: 2.6533,
    multiplier50: 11.4674,
    annualRate: 0.05,
    indexName: "オルカン",
    color: "text-green-500",
  },
];

export const COURSES_MAP = Object.fromEntries(
  COURSES.map((c) => [c.id, c])
) as Record<Course["id"], Course>;

export const CATEGORIES: Category[] = [
  { id: "food", label: "飲食・嗜好品", icon: "🍽️" },
  { id: "lifestyle", label: "ライフスタイル", icon: "🚶" },
  { id: "digital", label: "デジタル・固定費", icon: "💻" },
  { id: "social", label: "心理的・社会的", icon: "🧠" },
  { id: "entertainment", label: "娯楽", icon: "🎮" },
  { id: "transport", label: "交通費", icon: "🚃" },
  { id: "shopping", label: "買い物", icon: "🛍️" },
  { id: "health", label: "健康", icon: "💪" },
  { id: "other", label: "その他", icon: "📦" },
];

// 30〜50代子育て世帯向け ワンタップ節約スタンプ（20カテゴリー）
export const DEFAULT_STAMPS: Omit<Stamp, "id">[] = [
  // ── 飲食・嗜好品 ──
  {
    label: "自炊弁当",
    icon: "🍱",
    amount: 800,
    categoryId: "food",
    sortOrder: 0,
    isDefault: true,
    notificationMessage: "今日のお弁当づくり、お疲れさま。この800円が20年後には家族旅行の資金に変わります。",
  },
  {
    label: "晩酌休み",
    icon: "🍺",
    amount: 300,
    categoryId: "food",
    sortOrder: 1,
    isDefault: true,
    notificationMessage: "今夜はノンアル気分で。この300円が、未来の自分へのごほうびに育ちます。",
  },
  {
    label: "自宅ドリップ",
    icon: "☕",
    amount: 150,
    categoryId: "food",
    sortOrder: 2,
    isDefault: true,
    notificationMessage: "自宅で淹れた一杯の香り、最高ですよね。150円が未来を温めます。",
  },
  {
    label: "レジ横スイーツ",
    icon: "🍰",
    amount: 200,
    categoryId: "food",
    sortOrder: 3,
    isDefault: true,
    notificationMessage: "レジ横の誘惑をスルー。200円が未来のちょっと贅沢なディナーに。",
  },
  {
    label: "自販機スルー",
    icon: "🥤",
    amount: 160,
    categoryId: "food",
    sortOrder: 4,
    isDefault: true,
    notificationMessage: "マイボトルの一口が、未来の160円分の幸せに。ナイス判断！",
  },

  // ── ライフスタイル・時短 ──
  {
    label: "一駅歩き",
    icon: "🚶",
    amount: 200,
    categoryId: "lifestyle",
    sortOrder: 5,
    isDefault: true,
    notificationMessage: "歩いた分だけ健康と貯蓄のダブル貯金。200円を未来の自分にプレゼント。",
  },
  {
    label: "タクシー回避",
    icon: "🚕",
    amount: 4000,
    categoryId: "lifestyle",
    sortOrder: 6,
    isDefault: true,
    notificationMessage: "電車にして大正解。この4,000円は未来の家族のために大きく育ちます。",
  },
  {
    label: "手数料回避",
    icon: "💳",
    amount: 500,
    categoryId: "lifestyle",
    sortOrder: 7,
    isDefault: true,
    notificationMessage: "ムダな手数料をカット。500円を未来の自分への仕送りに。",
  },
  {
    label: "クリーニング自宅",
    icon: "👔",
    amount: 1000,
    categoryId: "lifestyle",
    sortOrder: 8,
    isDefault: true,
    notificationMessage: "自宅ケアでこの仕上がり、十分ですよね。1,000円が未来で花開きます。",
  },
  {
    label: "レジ袋パス",
    icon: "🛍️",
    amount: 10,
    categoryId: "lifestyle",
    sortOrder: 9,
    isDefault: true,
    notificationMessage: "エコバッグ持参で地球にも未来にもやさしく。小さな10円が積み重なります。",
  },

  // ── デジタル・固定費 ──
  {
    label: "サブスク解約",
    icon: "📱",
    amount: 1000,
    categoryId: "digital",
    sortOrder: 10,
    isDefault: true,
    notificationMessage: "使ってないサービスにさよなら。毎月1,000円が未来の資産形成に。",
  },
  {
    label: "ガチャ我慢",
    icon: "🎮",
    amount: 3000,
    categoryId: "digital",
    sortOrder: 11,
    isDefault: true,
    notificationMessage: "ガチャよりリアルな未来に投資。3,000円が将来の大きなリターンに変わります。",
  },
  {
    label: "ATM手数料",
    icon: "🏧",
    amount: 220,
    categoryId: "digital",
    sortOrder: 12,
    isDefault: true,
    notificationMessage: "手数料ゼロの引き出し、スマートです。220円を未来の自分に。",
  },
  {
    label: "図書館利用",
    icon: "📚",
    amount: 1500,
    categoryId: "digital",
    sortOrder: 13,
    isDefault: true,
    notificationMessage: "図書館で知識も節約も。1,500円分の本を無料で楽しめるなんて最高。",
  },
  {
    label: "格安プラン",
    icon: "📶",
    amount: 3000,
    categoryId: "digital",
    sortOrder: 14,
    isDefault: true,
    notificationMessage: "通信費の見直し、大きな一歩。毎月3,000円が未来の大きな差になります。",
  },

  // ── 心理的・社会的 ──
  {
    label: "二次会パス",
    icon: "🍻",
    amount: 3000,
    categoryId: "social",
    sortOrder: 15,
    isDefault: true,
    notificationMessage: "一次会で十分楽しんだ！3,000円を未来の自分へのプレゼントに。",
  },
  {
    label: "衝動買い我慢",
    icon: "🛒",
    amount: 5000,
    categoryId: "social",
    sortOrder: 16,
    isDefault: true,
    notificationMessage: "「本当に必要？」と問いかけた自分に拍手。5,000円が未来で大きく育ちます。",
  },
  {
    label: "セールスルー",
    icon: "🏷️",
    amount: 10000,
    categoryId: "social",
    sortOrder: 17,
    isDefault: true,
    notificationMessage: "安いから買うのではなく、必要だから買う。10,000円が未来の安心に。",
  },
  {
    label: "ホムパ化",
    icon: "🏠",
    amount: 2000,
    categoryId: "social",
    sortOrder: 18,
    isDefault: true,
    notificationMessage: "お家で楽しく過ごす選択、すてきです。2,000円が未来の家族の思い出に。",
  },
  {
    label: "節電意識",
    icon: "💡",
    amount: 100,
    categoryId: "social",
    sortOrder: 19,
    isDefault: true,
    notificationMessage: "こまめな節電は地球にも家計にもやさしい。100円の積み重ねが未来をつくります。",
  },
];
